rand<-runif(1)
cat("Random number:\t\t",rand,"\n")
rand<-(rand*10)
cat("Multiplied number:\t\t",rand,"\n")
rand<-ceiling(rand)
cat("Random integer:\t\t",rand,"\n\n")
nums <- c(1:59)
cat("My Lucky Numbers:",sample(nums,6),"\n\n")
nums <- rnorm(3)
cat("Random Normal distribution:",nums,"\n\n")
